
server:
  port: 8761

eureka:
  datacenter: trmap
  environment: product
  server:
    # Отключить самозащиту
    enable-self-preservation: false
    # Очистить сервер
    eviction-interval-timer-in-ms: 5000
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:user@localhost:8801/eureka/
    register-with-eureka: false
    fetch-registry: false

spring:
  security:
    basic:
      enabled: true
    user:
      name: user
      password: user
