spring:
  datasource:
    url: jdbc:h2:file:~/ClientService;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  application:
    name: ClientService

  security:
    user:
      name: user
      password: user

spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  #hibernate.ddl-auto: none
  #generate-ddl: false
  #properties.hibernate.hbm2ddl.auto: none

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://dubby:dubby@localhost:8761/eureka

server:
  port: 8801
