spring:
  security:
    basic:
      enabled: true
    user:
      name: user
      password: user

  datasource:
    url: jdbc:h2:file:~/ClientService;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  application:
    name: ClientService


spring.jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  #hibernate.ddl-auto: none
  #generate-ddl: false
  #properties.hibernate.hbm2ddl.auto: none

server:
  port: 8801

eureka:
  client:
    service-url:
      defaultZone: hhttp://user:user@localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
